-- Apollo Tyre Inspection PostgreSQL Phase 1 foundation.
-- Do not edit this file after it has been applied. Create a new numbered
-- migration for every later schema change.
-- {{schema}} is replaced safely by the migration runner.

CREATE TABLE IF NOT EXISTS {{schema}}.application_settings (
    setting_key        VARCHAR(150) PRIMARY KEY,
    setting_value      JSONB NOT NULL DEFAULT '{}'::jsonb,
    description        TEXT,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS {{schema}}.database_events (
    id                 BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    event_type         VARCHAR(80) NOT NULL,
    event_status       VARCHAR(30) NOT NULL,
    source_component   VARCHAR(150),
    event_data         JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_database_events_created_at
    ON {{schema}}.database_events (created_at DESC);

CREATE INDEX IF NOT EXISTS idx_database_events_type_status
    ON {{schema}}.database_events (event_type, event_status);

INSERT INTO {{schema}}.application_settings (
    setting_key,
    setting_value,
    description
)
VALUES (
    'postgres_phase',
    '{"phase": 1, "status": "foundation_ready"}'::jsonb,
    'Tracks the active PostgreSQL migration phase for Apollo Tyre Inspection.'
)
ON CONFLICT (setting_key) DO NOTHING;
