-- Apollo Tyre Inspection PostgreSQL Phase 2: SKU, recipe, active-recipe and device-profile data.
-- Do not edit this file after it has been applied. Create a new numbered
-- migration for every later schema change.
-- {{schema}} is replaced safely by the migration runner.

CREATE OR REPLACE FUNCTION {{schema}}.set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

CREATE TABLE IF NOT EXISTS {{schema}}.skus (
    id                       UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    sku_name                 VARCHAR(150) NOT NULL UNIQUE,
    recipe_number            INTEGER,
    plc_recipe_number        INTEGER,
    effective_recipe_number  INTEGER GENERATED ALWAYS AS (
        COALESCE(plc_recipe_number, recipe_number)
    ) STORED,
    tyre_name                VARCHAR(200),
    tyre_size                VARCHAR(100),
    tyre_outer_diameter      NUMERIC(14, 3),
    tyre_rpm                 NUMERIC(14, 3),
    barcode                  VARCHAR(250),
    barcode_pattern          VARCHAR(250),
    operator_name            VARCHAR(150),
    inspection_zones         SMALLINT NOT NULL DEFAULT 5,
    image_count_per_zone     INTEGER NOT NULL DEFAULT 20,
    train_good_count         INTEGER NOT NULL DEFAULT 0,
    status                   VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    sku_meta                 JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at               TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at               TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_skus_recipe_numbers_match CHECK (
        recipe_number IS NULL
        OR plc_recipe_number IS NULL
        OR recipe_number = plc_recipe_number
    ),
    CONSTRAINT ck_skus_inspection_zones_positive CHECK (inspection_zones > 0),
    CONSTRAINT ck_skus_image_count_positive CHECK (image_count_per_zone > 0),
    CONSTRAINT ck_skus_train_good_nonnegative CHECK (train_good_count >= 0),
    CONSTRAINT ck_skus_meta_object CHECK (jsonb_typeof(sku_meta) = 'object')
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_skus_effective_recipe_number
    ON {{schema}}.skus (effective_recipe_number)
    WHERE effective_recipe_number IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_skus_name_lower
    ON {{schema}}.skus (LOWER(sku_name));

CREATE INDEX IF NOT EXISTS idx_skus_status
    ON {{schema}}.skus (status);

CREATE INDEX IF NOT EXISTS idx_skus_meta_gin
    ON {{schema}}.skus USING GIN (sku_meta);

DROP TRIGGER IF EXISTS trg_skus_updated_at ON {{schema}}.skus;
CREATE TRIGGER trg_skus_updated_at
BEFORE UPDATE ON {{schema}}.skus
FOR EACH ROW EXECUTE FUNCTION {{schema}}.set_updated_at();

CREATE TABLE IF NOT EXISTS {{schema}}.sku_recipes (
    id                       UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    sku_id                   UUID NOT NULL REFERENCES {{schema}}.skus(id)
                                 ON UPDATE CASCADE ON DELETE RESTRICT,
    version                  INTEGER NOT NULL,
    status                   VARCHAR(30) NOT NULL DEFAULT 'DRAFT',
    author                   VARCHAR(150) NOT NULL DEFAULT 'operator',
    validation_score         DOUBLE PRECISION,
    modified_from_recipe_id  UUID REFERENCES {{schema}}.sku_recipes(id)
                                 ON UPDATE CASCADE ON DELETE SET NULL,
    recipe_document          JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at               TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at               TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_sku_recipes_sku_version UNIQUE (sku_id, version),
    CONSTRAINT ck_sku_recipes_version_positive CHECK (version > 0),
    CONSTRAINT ck_sku_recipes_document_object CHECK (
        jsonb_typeof(recipe_document) = 'object'
    )
);

CREATE INDEX IF NOT EXISTS idx_sku_recipes_sku_latest
    ON {{schema}}.sku_recipes (sku_id, version DESC);

CREATE INDEX IF NOT EXISTS idx_sku_recipes_status
    ON {{schema}}.sku_recipes (status);

CREATE INDEX IF NOT EXISTS idx_sku_recipes_document_gin
    ON {{schema}}.sku_recipes USING GIN (recipe_document);

DROP TRIGGER IF EXISTS trg_sku_recipes_updated_at ON {{schema}}.sku_recipes;
CREATE TRIGGER trg_sku_recipes_updated_at
BEFORE UPDATE ON {{schema}}.sku_recipes
FOR EACH ROW EXECUTE FUNCTION {{schema}}.set_updated_at();

CREATE TABLE IF NOT EXISTS {{schema}}.active_recipe_state (
    state_type       VARCHAR(50) PRIMARY KEY,
    recipe_id        UUID REFERENCES {{schema}}.sku_recipes(id)
                         ON UPDATE CASCADE ON DELETE SET NULL,
    sku_id           UUID REFERENCES {{schema}}.skus(id)
                         ON UPDATE CASCADE ON DELETE SET NULL,
    state_document   JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_active_recipe_state_type CHECK (
        state_type IN ('last_loaded_recipe', 'test_active_recipe')
    ),
    CONSTRAINT ck_active_recipe_state_document_object CHECK (
        jsonb_typeof(state_document) = 'object'
    )
);

CREATE INDEX IF NOT EXISTS idx_active_recipe_state_recipe
    ON {{schema}}.active_recipe_state (recipe_id);

DROP TRIGGER IF EXISTS trg_active_recipe_state_updated_at
    ON {{schema}}.active_recipe_state;
CREATE TRIGGER trg_active_recipe_state_updated_at
BEFORE UPDATE ON {{schema}}.active_recipe_state
FOR EACH ROW EXECUTE FUNCTION {{schema}}.set_updated_at();

CREATE TABLE IF NOT EXISTS {{schema}}.device_profiles (
    id                 UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    sku_id             UUID NOT NULL REFERENCES {{schema}}.skus(id)
                           ON UPDATE CASCADE ON DELETE CASCADE,
    profile_type       VARCHAR(20) NOT NULL,
    profile_version    INTEGER NOT NULL DEFAULT 1,
    json_path          TEXT,
    profile_document   JSONB NOT NULL DEFAULT '{}'::jsonb,
    is_active          BOOLEAN NOT NULL DEFAULT TRUE,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_device_profiles_sku_type UNIQUE (sku_id, profile_type),
    CONSTRAINT ck_device_profiles_type CHECK (
        profile_type IN ('CAMERA', 'LASER')
    ),
    CONSTRAINT ck_device_profiles_version_positive CHECK (profile_version > 0),
    CONSTRAINT ck_device_profiles_document_object CHECK (
        jsonb_typeof(profile_document) = 'object'
    )
);

CREATE INDEX IF NOT EXISTS idx_device_profiles_type_active
    ON {{schema}}.device_profiles (profile_type, is_active);

CREATE INDEX IF NOT EXISTS idx_device_profiles_document_gin
    ON {{schema}}.device_profiles USING GIN (profile_document);

DROP TRIGGER IF EXISTS trg_device_profiles_updated_at
    ON {{schema}}.device_profiles;
CREATE TRIGGER trg_device_profiles_updated_at
BEFORE UPDATE ON {{schema}}.device_profiles
FOR EACH ROW EXECUTE FUNCTION {{schema}}.set_updated_at();

INSERT INTO {{schema}}.application_settings (
    setting_key,
    setting_value,
    description
)
VALUES (
    'postgres_phase',
    '{"phase": 2, "status": "sku_recipe_device_ready"}'::jsonb,
    'Tracks the active PostgreSQL migration phase for Apollo Tyre Inspection.'
)
ON CONFLICT (setting_key) DO UPDATE SET
    setting_value = EXCLUDED.setting_value,
    description = EXCLUDED.description,
    updated_at = NOW();
